version: "3"
services:
  backend-app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
